import tkinter
import random
import time

def yeet():
    troll_fen = tkinter.Tk()
    troll_fen.title('LOL')
    troll_fen.geometry('200x140')
    troll_fen.minsize(200, 140)
    troll_fen.maxsize(200, 140)
    troll_fen.config(background='#333230')
    height = 200
    width = 140
    troll_txt = tkinter.Label(troll_fen, text='Still using this computer ?', fg='#FFFFFF',
                      font=("Pusia", 10), bg='#333230')
    troll_txt.pack()
    troll_btn = tkinter.Button(text='Ok', font=("Pusia", 15), bg='#F0F0F0', fg='#000000')
    troll_btn.pack(padx=7, pady=5)
    troll_fen.mainloop()


def yeet2():
    troll_fen2 = tkinter.Tk()
    troll_fen2.title('LOL')
    troll_fen2.geometry('200x140')
    troll_fen2.minsize(200, 140)
    troll_fen2.maxsize(200, 140)
    troll_fen2.config(background='#333230')
    height = 200
    width = 140
    troll_txt2 = tkinter.Label(troll_fen2, text='Still using this computer ?', fg='#FFFFFF',
                      font=("Pusia", 10), bg='#333230')
    troll_txt2.pack()
    troll_btn2 = tkinter.Button(text='Ok', font=("Pusia", 15), bg='#F0F0F0', fg='#000000')
    troll_btn2.pack(padx=7, pady=5)
    troll_can2 = tkinter.Canvas(troll_fen2, width=width, height=height, bg='#333230', bd=0, highlightthickness=0)
    troll_can2.pack()
    troll_fen2.mainloop()

while True:
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
    yeet()
    time.sleep(10)
    yeet2()
    time.sleep(10)
